version: "3"

services:
  postgres-server:
    image: postgres:14.0
    container_name: postgres-server
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: minsoo
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "minsoo", "-d", "mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  data-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-generator
    depends_on:
      postgres-server:
        condition: service_healthy
    command: ["postgres-server"]

networks:
  default:
    name: mlops-network